
###
POST http://localhost:3000/questions
Content-Type: application/json

{
    "category": "Technical Skills",
    "title": "Previous Work Experience",
    "description": "What job are you doing at the moment?",
    "criteria": [
        {"item": "No work experience at all", "value": 1},
        {"item": "Intern experience", "value": 2},
        {"item": "Less than 2 years in entry positions", "value": 3},
        {"item": "2+ years in mid to high level positions", "value": 4},
        {"item": "Combination of personal ventures & work", "value": 5}
    ],
    "priority": 1,
    "comment": "This should def be included in the tech skills calculation"
}


###
GET http://localhost:3000/questions/

###
GET http://localhost:3000/questions/5b4b245a8a353825721d6e2a

###
PUT http://localhost:3000/questions/5b4b245a8a353825721d6e2a
Content-Type: application/json

{
    "category": "Technical Skills1",
    "title": "Previous Work Experience1",
    "description": "What job are you doing at the moment?",
    "criteria": [
        {"item": "No work experience at all", "value": 1},
        {"item": "Intern experience", "value": 2},
        {"item": "Less than 2 years in entry positions", "value": 3},
        {"item": "2+ years in mid to high level positions", "value": 4},
        {"item": "Combination of personal ventures & work", "value": 5}
    ],
    "priority": 1,
    "comment": "This should def be included in the tech skills calculation"
}


###
PATCH http://localhost:3000/questions/5b4b245a8a353825721d6e2a
Content-Type: application/json

{
    "category": "Technical Skills1",
    "title": "Previous Work Experience1",
    "description": "1What job are you doing at the moment?"
}


###
DELETE http://localhost:3000/questions/5b4b245a8a353825721d6e2a



# ###
# GET http://localhost:3000/questions/
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbUBjb2RlcmFjYWRlbXkuY29tIiwiaXBfYWRkcmVzcyI6IjEyNy4wLjAuMSIsImlhdCI6MTUzMTMwOTkyNn0.mcI9iI6bJuRUO8FjUoTDDKTMld75ZAK04TThMaH4_nk

